describe('adicionar assinatura', () => {
  it('deve adicionar nova assinatura com sucesso', () => {
    cy.visit('/')
    cy.get('#login-email').type('email@teste.com')
    cy.get('#login-password').type('123456')
    cy.get('#login-form-element').submit()
    cy.screenshot('01-login-realizado')
    cy.get('[data-section="subscriptions"]').click()
    cy.screenshot('02-tela-assinaturas')
    cy.get('#add-subscription-btn').click()
    cy.screenshot('03-modal-aberto')
    cy.get('#service-name').type('Netflix')
    cy.get('#service-price').type('29.90')
    cy.get('#service-category').select('streaming')
    cy.screenshot('04-dados-preenchidos')
    cy.get('#subscription-form').submit()
    cy.get('#subscriptions-list').should('contain', 'Netflix')
    cy.screenshot('05-assinatura-adicionada')
  })
})