describe('remover assinatura', () => {
  it('deve remover assinatura com sucesso', () => {
    cy.visit('http://localhost:8080/')
    cy.get('#login-email').type('email@teste.com')
    cy.get('#login-password').type('123456')
    cy.get('#login-form-element').submit()
    cy.get('[data-section="subscriptions"]').click()
    cy.get('#add-subscription-btn').click()
    cy.get('#service-name').type('Spotify')
    cy.get('#service-price').type('19.90')
    cy.get('#service-category').select('music')
    cy.get('#subscription-form').submit()
    cy.get('.subscription-item').should('contain', 'Spotify')
    cy.get('.delete-btn').first().click()
    cy.get('#subscriptions-list').should('not.contain', 'Spotify')
  })
})